config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users, only: [:index, :show] do
    member do
      put "like"=> "users#upvote"
      put "unlike"=> "users#downvote"
    end
    resources :documents
  end

  authenticated :user do
    root 'users#dashboard', as: "authenticated_root"
  end

  root 'welcome#index'
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :user

  after_validation :clean_paperclip_errors

  validates :title,
          :presence => {:message => "El titulo no puede estar en blanco" },
          :length => { :in => 20..100, :message => "El titulo debe estar entre 20 a 100 caracteres"}

  validates :description,
          :presence => {:message => "La descripcion no puede estar en blanco" },
          :length => { :minimum => 20, :message => "La descripcion debe tener mas de 20 caracteres"}



  has_attached_file :pdf
  validates_attachment :pdf, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document), :message => 'Solo puedes subir archivos con formato .pdf' }

  private
  def clean_paperclip_errors
    errors.delete(:pdf)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  acts_as_votable
  acts_as_voter
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :documents
  has_attached_file :avatar, styles: { large: "1000x1000#", medium: "550x550#" }
  validates_attachment :avatar,
    content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:email, :password, :password_confirmation, :name, :last_name, :remember_me, :avatar)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:email, :password, :password_confirmation, :current_password, :facebook, :instagram, :name, :last_name, :avatar)}
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  require 'will_paginate/array'
  before_action :authenticate_user!, except: [:show]
  before_filter :require_permission, only: [:new]
  before_action :find_user
  before_action :find_document, only: [:show, :edit, :update, :destroy]

  def new
    @document = @user.documents.new
  end

  def create
    @document = @user.documents.new document_params
    if @document.save
        redirect_to user_document_path(@user, @document)
    else
      render 'new'
    end
  end
  def show
    @documents = Document.where(user_id: @user).order("created_at DESC").reject { |d| d.id == @document.id }
    @documents = @documents.paginate(:page => params[:page], :per_page => 5)
  end

  def edit
  end
  
  def update
    if @document.update document_params
      redirect_to user_document_path(@user, @document), notice: "El Documento fue editado con EXITO!"
    else
      render 'edit'
    end
  end
  def destroy
    @document.destroy
    redirect_to root_path

  end

  private

  def document_params
    params.require(:document).permit(:title, :description, :pdf)
  end

  def find_user
    @user = User.find(params[:user_id])
  end

  def find_document
    @document = Document.find(params[:id])
  end

  def require_permission
    @user = User.find(params[:user_id])
    if current_user != @user
      redirect_to root_path, notice: "Lo sentimos, no tienes permiso de ver esa pagina"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'will_paginate/array'
  before_action :find_user, only: [:show, :dashboard, :upvote, :downvote]
  before_action :find_document, only: [:show, :dashboard]


  def index
    if user_signed_in?
      @users = User.all.order(:cached_votes_up => :desc).reject { |u| u.id == current_user.id }
      @users = @users.paginate(:page => params[:page], :per_page => 8)
    else
      @users = User.all.order(:cached_votes_up => :desc).paginate(:page => params[:page], :per_page => 8)
    end
  end

  def show
  end

  def dashboard
  end

  #votos
  def upvote
    @user.upvote_from current_user
    redirect_to users_path
  end
  def downvote
    @user.downvote_from current_user
    redirect_to users_path
  end

  private

  def find_document
    @documents = Document.where(user_id: @user).order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
  end

  def find_user
    if params[:id].nil?
      @user= current_user
    else
      @user = User.find(params[:id])
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/documents/_form.html.erb
<div id="form">
  <div class="wrapper_skinny">
    <%= form_for ([@user, @document]) do |f| %>
    <% if @document.errors.any? %>
        <% @document.errors.messages.values.each do |msg|%>
            <%msg.each do |m|%>
            <div id="notice_wrapper_form">
              <p class="notice"> <%= m %></p>
            </div>
            <%end%>
        <%end%>
    <% end %>
      <div class="field">
        <%= f.text_field :title, placeholder:"Titulo del pdf"%>
      </div>
      <div class="field">
        <%= f.text_area :description, placeholder:"Descripcion del pdf"%>
      </div>
      <div class="field">
        <%= f.file_field :pdf, placeholder:"Sube el PDF"%>
      </div>
      <div class="actions">
        <%= f.submit class: "button button_new button_highlight" %>
      </div>
    <%end%>
  </div>
</div>

app/views/documents/edit.html.erb
<div class="wrapper_wide" id="homec">
<header class="cf">

    <%= link_to '#', :id => 'logo' do %>
      <span class="textodelgado">LIBRE</span> ESTUDIO
    <% end %>
      <nav class="navu">
        <ul>
          <li> <%= link_to "EXPLORA", users_path, class:"nav_button"%></li>
          <li> <%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class:"nav_button"%></li>
        </ul>
      </nav>
</header>
</div>
<div class="banner dashboard_banner" >
  <div class="avatar">
    <%=image_tag @user.avatar.url(:medium)%>

  </div>
  <div class="user_overview">
      <p>
        <%= @user.name%> <%= @user.last_name%>
      </p>
          <%unless @user.facebook.blank?%>
            <a href="<%=@user.facebook%>", class=" button_edit" target="_blank">Facebook</a>
          <%end%>
          <%unless @user.instagram.blank?%>
            <a href="<%=@user.instagram%>", class=" button_edit" target="_blank">Instagram</a>
          <%end%>
  </div>
</div>
<div id="links">
  <div class="wrapper_skinny">
    <ul>
      <li><%= link_to "Documentos", root_path%></li>
      <span class="colorgray">/</span>
      <li><%= link_to "Subir Documento",  new_user_document_path( @user ) %></li>
      <span class="colorgray">/</span>
      <li><%= link_to "Account Settings", edit_user_registration_path %></li>

    </ul>
  </div>
</div>
<div class="hr wrapper_skinny">
  <span> </span>
      ¿Editando?
  <span></span>
</div>
<%=render 'form'%>

app/views/documents/new.html.erb
<div class="wrapper_wide" id="homec">
<header class="cf">

    <%= link_to '#', :id => 'logo' do %>
      <span class="textodelgado">LIBRE</span> ESTUDIO
    <% end %>
      <nav class="navu">
        <ul>
          <li> <%= link_to "EXPLORA", users_path, class:"nav_button"%></li>
          <li> <%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class:"nav_button"%></li>
        </ul>
      </nav>
</header>
</div>
<div class="banner dashboard_banner" >
  <div class="avatar">
    <%=image_tag @user.avatar.url(:medium)%>
  </div>
  <div class="user_overview">
      <p>
        <%= @user.name%> <%= @user.last_name%>
        <div class="votesuser">
          <svg class="upvotes"></svg><span><%=current_user.get_upvotes.size%></span>
          <span>/</span>
          <svg class="downvotes"></svg><span><%=current_user.get_downvotes.size%></span>
        </div>
      </p>
          <%unless @user.facebook.blank?%>
            <a href="<%=@user.facebook%>", class=" button_edit" target="_blank">Facebook</a>
          <%end%>
          <%unless @user.instagram.blank?%>
            <a href="<%=@user.instagram%>", class=" button_edit" target="_blank">Instagram</a>
          <%end%>
  </div>
</div>
<div id="links">
  <div class="wrapper_skinny">
    <ul>
      <li><%= link_to "Documentos", root_path%></li>
      <span class="colorgray">/</span>
      <li> <a href="#" class="current">Subir Documento</a></li>
      <span class="colorgray">/</span>
      <li><%= link_to "Editar Cuenta", edit_user_registration_path %></li>

    </ul>
  </div>
</div>
<div class="hr wrapper_skinny">
  <span> </span>
      Comparte!
  <span></span>
</div>
<%=render 'form'%>

app/views/documents/show.html.erb
<div class="wrapper_wide" id="homec">
  <div class="mobile-nav">
    <nav class="navum">
      <ul>
        <% unless user_signed_in?%>
          <li> <%= link_to "EXPLORA", users_path, class:"nav_button"%></li>
          <li> <%= link_to "LOG IN", new_user_session_path, class:"nav_button"%></li>

        <%else%>
          <li> <%= link_to "EXPLORA", users_path, class:"nav_button"%></li>
          <li> <%= link_to "DASHBOARD", root_path, class:"nav_button"%></li>
          <li> <%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class:"nav_button"%></li>

        <%end%>
      </ul>
    </nav>
  </div>
  <header class="cf">

      <%= link_to '#', :id => 'logo' do %>
        <span class="textodelgado">LIBRE</span> ESTUDIO
      <% end %>
        <nav class="navu">
          <ul>
            <% unless user_signed_in?%>
              <li> <%= link_to "EXPLORA", users_path, class:"nav_button"%></li>
              <li> <%= link_to "LOG IN", new_user_session_path, class:"nav_button"%></li>

            <%else%>
              <li> <%= link_to "EXPLORA", users_path, class:"nav_button"%></li>
              <li> <%= link_to "DASHBOARD", root_path, class:"nav_button"%></li>
              <li> <%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class:"nav_button"%></li>

            <%end%>

          </ul>
        </nav>
      <div class="mobile-nav-t">
        <span></span>
      </div>
  </header>
</div>
<div class="banner dashboard_banner" >
  <div class="avatar">
    <%=image_tag @user.avatar.url(:medium)%>

  </div>
    <div class="user_overview">
          <p>
            <%= @user.name%> <%= @user.last_name%>
            <div class="votesuser">
              <svg class="upvotes"></svg><span><%=@user.get_upvotes.size%></span>
              <span>/</span>
              <svg class="downvotes"></svg><span><%=@user.get_downvotes.size%></span>
            </div>
          </p>
          <% unless @user.facebook.blank?%>
            <a href="<%= @user.facebook%>" class="button_edit" target="_blank">Facebook</a>
          <%end%>
          <% unless @user.instagram.blank?%>
            <a href="<%= @user.instagram%>" class="button_edit" target="_blank">instagram</a>
          <%end%>
    </div>
  </div>
</div>

<div id="breadcrumb">
  <div class="wrapperm">
    <%=link_to users_path do%>
      All Users
      <span>/</span>
       Perfil de <span class="textodelgado"><%= @user.name %> <%= @user.last_name %></span>
      <a href="#"><span>/</span><span class="textodelgado"><%= @document.title %> </span></a>
    <%end%>
  </div>
</div>
<div id="unidades" class="wrapper ">
  <div class="wapper_skinny">
    <ul class="cf">
        <li class="cf">
          <div class="documento_thumbnail">
          </div>
          <div class="documento_overview">
            <h1><%= @document.title%></h1>
            <p class="des_documento">
              <%=@document.description%>
            </p>
            <% if user_signed_in?%>
            <div class="authorized_links">
              <%= link_to "DESCARGAR", @document.pdf.url(:original, false), :target => "_blank"%>
            </div>
            <%end%>
          </div>
        </li>

    </ul>
  </div>
</div>
<div id="documentos">
  <div class="wrapper_skinny">
    <ul class="cf">
      <% @documents.each do |document|%>
        <li class="cf">
          <div class="documento_thumbnail"></div>
          <div class="documento_overview">
            <h2><%= link_to document.title, user_document_path(@user, document)%></h2>
            <p class="des_documento">
              <%=truncate(document.description, length:150)%>
            </p>
          </div>
        </li>
      <%end%>
    </ul>
  </div>
</div>
<%= will_paginate @documents, previous_label: "Anterior", next_label: "Siguiente" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Libre Estudio</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>

    <% if notice %>
        <div id="notice_wrapper">
          <p class="notice"><%= notice %></p>
        </div>
      <%elsif alert%>
      <div id="notice_wrapper">
        <p class="alert"><%= alert %></p>
      </div>
    <%end%>


  <%= yield %>

  <script type="text/javascript" data-turbolinks-eval=always>
     console.log("I'm run on every page load, including history back/forward");
     $('.mobile-nav-t').on ('click',function(){

       $('.mobile-nav').toggleClass('is-open');
       $('.mobile-nav-t').toggleClass('is-open');

     });
   </script>

  </body>
</html>

app/views/users/dashboard.html.erb
<div class="wrapper_wide" id="homec">
  <div class="mobile-nav">
    <nav class="navum">
      <ul>
        <li> <%= link_to "EXPLORA", users_path, class:"nav_button"%></li>
        <li> <%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class:"nav_button"%></li>
      </ul>
    </nav>
  </div>
<header class="cf">

  <%= link_to root_path, :id => 'logo' do %>
      <span class="textodelgado">LIBRE</span> ESTUDIO
    <% end %>
      <nav class="navu">
        <ul>
          <li> <%= link_to "EXPLORA", users_path, class:"nav_button"%></li>
          <li> <%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class:"nav_button"%></li>
        </ul>
      </nav>
    <div class="mobile-nav-t">
      <span></span>
    </div>
</header>
</div>
<div class="banner dashboard_banner" >
  <div class="avatar">
      <%=image_tag current_user.avatar.url(:medium)%>
  </div>
  <div class="user_overview">
      <p>
        <%= @user.name%> <%= @user.last_name%> <br>
        <div class="votesuser">
          <svg class="upvotes"></svg><span><%=current_user.get_upvotes.size%></span>
          <span>/</span>
          <svg class="downvotes"></svg><span><%=current_user.get_downvotes.size%></span>
        </div>
      </p>

  </div>
  <div class= "redes ">
  <%unless @user.facebook.blank?%>
    <a href="<%=@user.facebook%>", class=" button_edit" target="_blank">Facebook</a>
  <%end%>
  <%unless @user.instagram.blank?%>
    <a href="<%=@user.instagram%>", class=" button_edit" target="_blank">Instagram</a>
  <%end%>
  </div>
</div>
<div id="links">
  <div class="wrapper_skinny">
    <ul>
      <li ><a href="#"class="current" >Documentos</a></li>
      <span class="colorgray">/</span>
      <li><%= link_to "Subir Documento",  new_user_document_path( @user ) %></li>
      <span class="colorgray">/</span>
      <li><%= link_to "Editar Cuenta", edit_user_registration_path%></li>
    </ul>
  </div>
</div>

<div id="documentos">
  <div class="wrapper_skinny">
    <ul class="cf">
        <% @documents.each do |document|%>
          <li class="cf">
            <div class="documento_thumbnail">
            </div>
            <div class="documento_overview">
              <h2><%= link_to document.title, user_document_path(@user, document)%></h2>
              <p class="des_documento">
                <%=truncate(document.description, length:150)%>
              </p>
              <div class="authorized_links">
                <%= link_to "Editar", edit_user_document_path(@user, document)%>
                <%= link_to "Borrar", user_document_path(@user, document), method: :delete, data: {confirm: "¿Seguro quieres eliminar el archivo?"}%>
              </div>
            </div>
          </li>
        <%end%>
    </ul>
  </div>
</div>

<%= will_paginate @documents, previous_label: "Anterior", next_label: "Siguiente" %>

app/views/users/index.html.erb
<div class="wrapper_wide" id="homec">
  <div class="mobile-nav">
    <nav class="navum">
      <ul>
        <% unless user_signed_in?%>
          <li> <%= link_to "LOG IN", new_user_session_path, class:"nav_button"%></li>

        <%else%>
          <li> <%= link_to "DASHBOARD", root_path, class:"nav_button"%></li>
          <li> <%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class:"nav_button"%></li>
        <%end%>
      </ul>
    </nav>
  </div>
<header class="cf">

  <%= link_to root_path, :id => 'logo' do %>
      <span class="textodelgado">LIBRE</span> ESTUDIO
  <% end %>
  <nav class="navu">
    <ul>
      <% unless user_signed_in?%>
        <li> <%= link_to "LOG IN", new_user_session_path, class:"nav_button"%></li>

      <%else%>
        <li> <%= link_to "DASHBOARD", root_path, class:"nav_button"%></li>
        <li> <%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class:"nav_button"%></li>
      <%end%>
    </ul>


  </nav>
  <div class="mobile-nav-t">
    <span></span>
  </div>
</header>
</div>
<div class="banner categorias_banner" ></div>
<div class="cf" id="documento">
  <div class="wrapper">
    <ul class="cf">
      <% @users.each do |user|%>
        <%= link_to user do%>
          <li>
            <%=image_tag user.avatar.url(:medium)%>
            <div class="user_overview">
              <h2><%= user.name%> <%=user.last_name%></h2>
              <p class="document_count">
              Documentos:  <%= user.documents.size%>
              </p>
              <% if user_signed_in?%>
                <div class="votes">
                  <%= link_to like_user_path(user), class:"like", method: :put do %>
                  <svg id="happyface"></svg>
                  <span><%=user.get_upvotes.size%></span>
                  <%end%>
                  <%= link_to unlike_user_path(user), class:"unlike", method: :put do %>
                  <div id="unlikevotes">
                    <svg id="sadface"></svg>
                    <span><%=user.get_downvotes.size%></span>
                  </div>
                  <%end%>
                </div>
              <%else%>
                <div class="votes">
                  <div class="like ">
                    <svg id="happyface" class="no_click"></svg>
                    <span><%=user.get_upvotes.size%></span>
                  </div>
                  <div class="unlike ">
                    <svg id="sadface" class="no_click"></svg>
                    <span><%=user.get_downvotes.size%></span>
                  </div>
                </div>
              <%end%>
            </div>
          </li>
        <%end%>
      <%end%>
    </ul>
    <%= will_paginate @users, previous_label: "Anterior", next_label: "Siguiente" %>
  </div>

</div>

app/views/users/show.html.erb
<div class="wrapper_wide" id="homec">
  <div class="mobile-nav">
    <nav class="navum">
      <ul>
        <% unless user_signed_in?%>
          <li> <%= link_to "EXPLORA", users_path, class:"nav_button"%></li>
          <li> <%= link_to "LOG IN", new_user_session_path, class:"nav_button"%></li>
        <%else%>
          <li> <%= link_to "EXPLORA", users_path, class:"nav_button"%></li>
          <li> <%= link_to "DASHBOARD", root_path, class:"nav_button"%></li>
          <li> <%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class:"nav_button"%></li>
        <%end%>
      </ul>
    </nav>
  </div>
  <header class="cf">

      <%= link_to root_path, :id => 'logo' do %>
        <span class="textodelgado">LIBRE</span> ESTUDIO
      <% end %>
        <nav class="navu">
          <ul>
            <% unless user_signed_in?%>
              <li> <%= link_to "EXPLORA", users_path, class:"nav_button"%></li>
              <li> <%= link_to "LOG IN", new_user_session_path, class:"nav_button"%></li>
            <%else%>
              <li> <%= link_to "EXPLORA", users_path, class:"nav_button"%></li>
              <li> <%= link_to "DASHBOARD", root_path, class:"nav_button"%></li>
              <li> <%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class:"nav_button"%></li>
            <%end%>
          </ul>
        </nav>
        <div class="mobile-nav-t">
          <span></span>
        </div>
  </header>
</div>
<div class="banner dashboard_banner" >
  <div class="avatar">
    <%=image_tag @user.avatar.url(:medium)%>
  </div>
  <div class="user_overview">
        <p>
          <%= @user.name%> <%= @user.last_name%>
          <div class="votesuser">
            <svg class="upvotes"></svg><span><%=@user.get_upvotes.size%></span>
            <span>/</span>
            <svg class="downvotes"></svg><span><%=@user.get_downvotes.size%></span>
          </div>
        </p>
        <% unless @user.facebook.blank?%>
          <a href="<%= @user.facebook%>" class="button_edit" target="_blank">Facebook</a>
        <%end%>
        <% unless @user.instagram.blank?%>
          <a href="<%= @user.instagram%>" class="button_edit" target="_blank">instagram</a>
        <%end%>
  </div>
  </div>
</div>

<div id="breadcrumb">
  <div class="wrapperm">
    <%=link_to users_path do%>
      All Users
      <span>/</span>
      Perfil de <span class="textodelgado"><%= @user.name %> <%= @user.last_name %></span>
    <%end%>
  </div>
</div>
<div id="documentos">
  <div class="wrapper_skinny">
    <ul class="cf">
        <% @documents.each do |document|%>
          <li class="cf">
            <div class="documento_thumbnail">
            </div>
            <div class="documento_overview">
              <h2><%= link_to document.title, user_document_path(@user, document)%></h2>
              <p class="des_documento">
                <%=truncate(document.description, length:150)%>
              </p>
            </div>
          </li>
        <%end%>
    </ul>
  </div>
</div>

<%= will_paginate @documents, previous_label: "Anterior", next_label: "Siguiente" %>

app/views/welcome/index.html.erb
<div class="wrapper_wide" id="homec">
  <div class="mobile-nav">
    <nav class="navum">
      <ul>
        <% unless user_signed_in? %>
          <li><%= link_to "LOG IN", new_user_session_path, class:"nav_button" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
<header class="cf">
    <a href="#" id="logo"> <span class="textodelgado">LIBRE</span> ESTUDIO</a>
      <nav class="navu">
        <ul>
          <% unless user_signed_in? %>
            <li><%= link_to "LOG IN", new_user_session_path, class:"nav_button" %></li>
          <% end %>
        </ul>
      </nav>
  <div class="mobile-nav-t">
    <span></span>
  </div>
</header>
</div>
<div class="wrapper_wide">
  <section id="contenido">
    <h1><span class="textongrueso">ÚNETE A</span> <span class="textodelgado">LIBRE</span> ESTUDIO</h1>
    <p id=desproyecto>
      Una comunidad donde encontraras <span class="textodelgado">TODO</span> (material practico y teórico)<br>
      sobre Lenguaje de Programación I siguiendo con los estatutos<br>
      encontrados en el pensum del <span class="textodelgado">Primer Semestre</span> de la carrera de Informática <br>
      del Instituto Universitario de Tecnología Industrial Rodolfo Loero Arismendi <br>
      <span class="textodelgado">(I.U.T.I.R.L.A)</span>.
    </p>
    <div class="wrapper_wide">
      <% unless user_signed_in?%>
        <%= link_to "Regístrate", new_user_registration_path, class:"button button_highlight button_home " %>
        <%= link_to "Explora", users_path, class:"button button_highlight button_home"%>

      <%end%>

    </div>
    <div id="warning" class="wrapper_wide">
      <p>
        Para disfrutar del contenido descargable deberás regístrarte
      </p>
    </div>

  </section>
  <div id="logo_wrapper"></div>
</div>